//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
namespace MoIS.Models
{
    using System;
    using System.Collections.Generic;

    public partial class butiranpengurusmayat
    {
        public int PM_ID { get; set; }
        [DisplayName("Nama Syarikat/Individu")]
        public string Syarikat_Individu { get; set; }
        [DisplayName("Nama Pemandu")]
        public string Pemandu { get; set; }
        [DisplayName("No. Telefon")]
        public string PhoneNO { get; set; }
        [DisplayName("No. Kad Pengenalan")]
        public string NoIC { get; set; }
        [DisplayName("Tarikh dan Masa")]
        public string DateTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> DeceasedID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<short> Status { get; set; }

        public virtual medicalassistant medicalassistant { get; set; }
        public virtual deceased deceased { get; set; }
        public virtual medicalassistant medicalassistant1 { get; set; }
    }
}
