//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;
namespace MoIS.Models
{
    using System;
    using System.Collections.Generic;

    public partial class butiranbedahsiasat
    {
        public int BsID { get; set; }
        [DisplayName("No. Bedah Siasat")]
        public string NoBedahSiasat { get; set; }
        [DisplayName("Tarikh dan Masa Bedah Siasat")]
        public Nullable<System.DateTime> DateTimeBS { get; set; }
        [DisplayName("No. Laporan Polis")]
        public string NoLaporanPolis { get; set; }
        [DisplayName("Tarik dan Masa Laopran Polis")]
        public Nullable<System.DateTime> DateTimePOL { get; set; }
        public Nullable<int> DeceasedID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<short> Status { get; set; }

        public virtual deceased deceased { get; set; }
        public virtual medicalassistant medicalassistant { get; set; }
        public virtual medicalassistant medicalassistant1 { get; set; }
    }
}
