//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class butiranwari
    {
        public butiranwari()
        {
            this.permohonansimpanmayats = new HashSet<permohonansimpanmayat>();
            this.permohonanbilliks = new HashSet<permohonanbillik>();
        }
    
        public int WarisID { get; set; }
        public string WarisName { get; set; }
        public string WarisNoIC { get; set; }
        public string Alamat { get; set; }
        public string PhoneNo { get; set; }
        public string Perhubungan { get; set; }
        public Nullable<System.DateTime> DateTimeRequest { get; set; }
        public Nullable<System.DateTime> DateTimeReturn { get; set; }
        public Nullable<int> ReturnedBy { get; set; }
        public Nullable<int> DeceasedID { get; set; }
        public byte[] Signature { get; set; }
        public Nullable<int> Editedby { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<short> Status { get; set; }
    
        public virtual deceased deceased { get; set; }
        public virtual medicalassistant medicalassistant { get; set; }
        public virtual medicalassistant medicalassistant1 { get; set; }
        public virtual ICollection<permohonansimpanmayat> permohonansimpanmayats { get; set; }
        public virtual ICollection<permohonanbillik> permohonanbilliks { get; set; }
    }
}
