//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModels : DbContext
    {
        public DBModels()
            : base("name=DBModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<butiranbedahsiasat> butiranbedahsiasats { get; set; }
        public DbSet<butiranmcdpmc> butiranmcdpmcs { get; set; }
        public DbSet<butiranpengurusmayat> butiranpengurusmayats { get; set; }
        public DbSet<butiranwari> butiranwaris { get; set; }
        public DbSet<city> cities { get; set; }
        public DbSet<deceased> deceaseds { get; set; }
        public DbSet<medicalassistant> medicalassistants { get; set; }
        public DbSet<pengecamansemula> pengecamansemulas { get; set; }
        public DbSet<postcode> postcodes { get; set; }
        public DbSet<state> states { get; set; }
    }
}
