//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deceased
    {
        public deceased()
        {
            this.butiranbedahsiasats = new HashSet<butiranbedahsiasat>();
            this.butiranmcdpmcs = new HashSet<butiranmcdpmc>();
            this.butiranpengurusmayats = new HashSet<butiranpengurusmayat>();
            this.butiranwaris = new HashSet<butiranwari>();
            this.pengecamansemulas = new HashSet<pengecamansemula>();
            this.permohonansimpanmayats = new HashSet<permohonansimpanmayat>();
            this.permohonanbilliks = new HashSet<permohonanbillik>();
        }
    
        public int DeceasedID { get; set; }
        public string DeceasedName { get; set; }
        public string Address { get; set; }
        public Nullable<int> Postcode { get; set; }
        public string Nationality { get; set; }
        public string NoIC { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Race { get; set; }
        public string Religion { get; set; }
        public Nullable<System.DateTime> DateOfWad { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public System.DateTime DateOfRegistration { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime DateOfLastModified { get; set; }
        public int ModifiedBy { get; set; }
        public int TypeOfCase { get; set; }
        public System.DateTime DateOfReceived { get; set; }
        public string WadUnit { get; set; }
        public string NoOfHospitalRegister { get; set; }
        public byte[] qrcode { get; set; }
        public Nullable<short> Status { get; set; }
    
        public virtual ICollection<butiranbedahsiasat> butiranbedahsiasats { get; set; }
        public virtual ICollection<butiranmcdpmc> butiranmcdpmcs { get; set; }
        public virtual ICollection<butiranpengurusmayat> butiranpengurusmayats { get; set; }
        public virtual ICollection<butiranwari> butiranwaris { get; set; }
        public virtual medicalassistant medicalassistant { get; set; }
        public virtual ICollection<pengecamansemula> pengecamansemulas { get; set; }
        public virtual ICollection<permohonansimpanmayat> permohonansimpanmayats { get; set; }
        public virtual ICollection<permohonanbillik> permohonanbilliks { get; set; }
        public virtual medicalassistant medicalassistant1 { get; set; }
        public virtual postcode postcode1 { get; set; }
    }
}
