//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int log_id { get; set; }
        public string name { get; set; }
        public string content { get; set; }
        public string header { get; set; }
        public string body { get; set; }
        public string ip { get; set; }
        public string url { get; set; }
        public Nullable<int> user { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<short> status { get; set; }
    }
}
