//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class medicalassistant
    {
        public medicalassistant()
        {
            this.butiranbedahsiasats = new HashSet<butiranbedahsiasat>();
            this.butiranbedahsiasats1 = new HashSet<butiranbedahsiasat>();
            this.butiranmcdpmcs = new HashSet<butiranmcdpmc>();
            this.butiranmcdpmcs1 = new HashSet<butiranmcdpmc>();
            this.butiranpengurusmayats = new HashSet<butiranpengurusmayat>();
            this.butiranpengurusmayats1 = new HashSet<butiranpengurusmayat>();
            this.butiranwaris = new HashSet<butiranwari>();
            this.butiranwaris1 = new HashSet<butiranwari>();
            this.deceaseds = new HashSet<deceased>();
            this.deceaseds1 = new HashSet<deceased>();
            this.pengecamansemulas = new HashSet<pengecamansemula>();
            this.pengecamansemulas1 = new HashSet<pengecamansemula>();
        }

        public int MaID { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string MaName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Username: ")]
        public string Username { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        //[StringLength(150, MinimumLength = 6)]
        [Display(Name = "Password: ")]
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        [Required(ErrorMessage = "This field is required")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password: ")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        public string LoginErrorMessage { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string MaIcNo { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string Role { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public Nullable<short> Status { get; set; }

        public virtual ICollection<butiranbedahsiasat> butiranbedahsiasats { get; set; }
        public virtual ICollection<butiranbedahsiasat> butiranbedahsiasats1 { get; set; }
        public virtual ICollection<butiranmcdpmc> butiranmcdpmcs { get; set; }
        public virtual ICollection<butiranmcdpmc> butiranmcdpmcs1 { get; set; }
        public virtual ICollection<butiranpengurusmayat> butiranpengurusmayats { get; set; }
        public virtual ICollection<butiranpengurusmayat> butiranpengurusmayats1 { get; set; }
        public virtual ICollection<butiranwari> butiranwaris { get; set; }
        public virtual ICollection<butiranwari> butiranwaris1 { get; set; }
        public virtual ICollection<deceased> deceaseds { get; set; }
        public virtual ICollection<deceased> deceaseds1 { get; set; }
        public virtual ICollection<pengecamansemula> pengecamansemulas { get; set; }
        public virtual ICollection<pengecamansemula> pengecamansemulas1 { get; set; }
    }
}
