//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pengecamansemula
    {
        public int CaseID { get; set; }
        public string LabelMayat { get; set; }
        public string PengecamanMukaSimati { get; set; }
        public string Pakaian { get; set; }
        public string Lain_lainCara { get; set; }
        public Nullable<int> DeceasedID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual deceased deceased { get; set; }
        public virtual medicalassistant medicalassistant { get; set; }
        public virtual medicalassistant medicalassistant1 { get; set; }
    }
}
