//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class postcode
    {
        public postcode()
        {
            this.deceaseds = new HashSet<deceased>();
        }
    
        public int Postcode1 { get; set; }
        public int CityID { get; set; }
        public int StateID { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<deceased> deceaseds { get; set; }
        public virtual state state { get; set; }
    }
}
